/**
 * seed-phase2.ts
 * Seeds 23 Phase 2 verified-launch countries with official-source backed policy data.
 * Run after: npx prisma db push (to ensure VISA_ON_ARRIVAL enum is in DB)
 *
 * DATABASE_URL="..." npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/seed-phase2.ts
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const VERIFIED_AT = new Date("2026-04-22");

function computeFreshness(verifiedAt: Date): string {
  const daysSince = (Date.now() - verifiedAt.getTime()) / (1000 * 60 * 60 * 24);
  if (daysSince <= 14) return "fresh";
  if (daysSince <= 30) return "stale";
  return "needs_review";
}

function nextRefresh(cadence: string, from: Date): Date {
  const d = new Date(from);
  if (cadence === "weekly") d.setDate(d.getDate() + 7);
  else if (cadence === "biweekly") d.setDate(d.getDate() + 14);
  else d.setDate(d.getDate() + 30);
  return d;
}

function mapVisaCategory(cat: string): string {
  switch (cat) {
    case "e_visa": return "E_VISA";
    case "visa_free": return "VISA_EXEMPT";
    case "visa_on_arrival": return "VISA_ON_ARRIVAL";
    case "visa_required": return "REQUIRED";
    default: return "REQUIRED";
  }
}

const PHASE2_DATA = [
  {
    iso2: "LK", priorityRank: 11, launchBucket: "regional_volume",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "ETA for short visits",
      officialSourceUrl: "https://eta.gov.lk/",
      officialSourceSummary: "Sri Lanka requires an Electronic Travel Authorization (ETA) for short visits; the official ETA portal says tourists can obtain ETA online before travel.",
      applyMode: "Official ETA application before travel; some mission-assisted routes also exist.",
      stayValiditySummary: "Tourist ETA route generally supports short visits; official portal messaging currently references a 30-day tourist stay.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Arrival and departure details", "Contact information"],
      coreChecklist: ["Valid passport", "ETA application details", "Return/onward travel", "Accommodation details"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket ETA assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Keep a freshness banner because Sri Lanka has changed short-visit visa handling multiple times.",
    },
  },
  {
    iso2: "MY", priorityRank: 12, launchBucket: "regional_volume",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "visa_free",
    policy: {
      productLabel: "Visa exemption until 31 Dec 2026 + MDAC",
      officialSourceUrl: "https://www.imi.gov.my/index.php/en/main-services/visa/visa-requirement-by-country/",
      officialSourceSummary: "Malaysia Immigration states that Indian citizens are visa-exempt until 31 December 2026 for the relevant social visit route; travellers also need Malaysia Digital Arrival Card compliance where applicable.",
      applyMode: "No visa for eligible short social visits during the exemption period; MDAC and entry conditions still apply.",
      stayValiditySummary: "Short social visit route during the exemption window; longer or different-purpose stays require the appropriate visa/pass.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Flight details", "Accommodation details"],
      coreChecklist: ["Valid passport", "MDAC submission", "Return/onward ticket", "Proof of funds if requested"],
      opsRouting: "info_only_or_light_support",
      paymentModelHint: "Low-ticket assistance or travel-readiness upsell",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official immigration portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Time-bound exemption. Surface the expiry date prominently.",
    },
  },
  {
    iso2: "ID", priorityRank: 13, launchBucket: "regional_volume",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "e-VOA / e-Visa online",
      officialSourceUrl: "https://evisa.imigrasi.go.id/",
      officialSourceSummary: "Indonesia's official e-Visa platform allows online visa application, and the official Indonesia e-VOA route is also publicly available for eligible travellers.",
      applyMode: "Online application through the immigration e-Visa platform or e-VOA route depending on product chosen.",
      stayValiditySummary: "Tourism routes vary by visa product; traveller must choose the correct visa class and validity.",
      coreCustomerInputs: ["Passport biodata page", "Recent photo", "Travel dates", "Return ticket", "Accommodation details"],
      coreChecklist: ["Valid passport with required validity", "Photo", "Return/onward travel", "Accommodation details", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket self-serve or concierge assistance",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official immigration portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Bali-related entry formalities and declarations can shift. Keep rule versioning tight.",
    },
  },
  {
    iso2: "VN", priorityRank: 14, launchBucket: "digital_visa_growth",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "National e-Visa",
      officialSourceUrl: "https://evisa.gov.vn/",
      officialSourceSummary: "Vietnam's national e-Visa system says e-Visas are valid for up to 90 days, single or multiple entry, for eligible foreign passport holders.",
      applyMode: "Direct online e-Visa application via the national immigration portal.",
      stayValiditySummary: "Up to 90 days, single or multiple entry depending on the approved e-Visa.",
      coreCustomerInputs: ["Passport biodata page", "Portrait photo", "Travel dates", "Port of entry", "Accommodation details"],
      coreChecklist: ["Valid passport", "Photo meeting spec", "Port selection", "Travel itinerary", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket e-Visa processing assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official e-visa portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Good candidate for a very clean automated customer flow.",
    },
  },
  {
    iso2: "JP", priorityRank: 15, launchBucket: "premium_high_trust",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "Japan eVISA for short-term tourism",
      officialSourceUrl: "https://www.in.emb-japan.go.jp/itpr_ja/11_000001_01148.html",
      officialSourceSummary: "The Embassy of Japan in India says Japan eVISA started in India from 1 April 2024 for single-entry short-term tourism, up to 90 days, with submission handled through Japan Visa Application Centers.",
      applyMode: "Apply through the Japan visa process in India; visa may be issued in electronic form for eligible tourism cases.",
      stayValiditySummary: "Single-entry short-term tourism route, up to 90 days.",
      coreCustomerInputs: ["Passport biodata page", "Travel itinerary", "Financial documents", "Employment details", "Travel dates"],
      coreChecklist: ["Valid passport", "Application form", "Photo", "Itinerary", "Financial proof", "Supporting travel documents"],
      opsRouting: "digital_plus_document_review",
      paymentModelHint: "Mid-ticket guided application",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "embassy page",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Operationally treat as premium, documentation-sensitive, and schedule-aware.",
    },
  },
  {
    iso2: "KR", priorityRank: 16, launchBucket: "premium_high_trust",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "visa_required",
    policy: {
      productLabel: "Tourist visa via Korea Visa Application Center",
      officialSourceUrl: "https://www.visaforkorea-id.com/",
      officialSourceSummary: "The official Korea Visa Application Center site for India says travellers can apply for a visa through the center, with application flow and fee guidance handled there.",
      applyMode: "Center-based application with document submission through the official partner channel in India.",
      stayValiditySummary: "Validity and stay depend on the granted visa class and consular decision.",
      coreCustomerInputs: ["Passport biodata page", "Travel itinerary", "Financial documents", "Employment/student proof", "Travel dates"],
      coreChecklist: ["Valid passport", "Visa application form", "Photo", "Flight and accommodation details", "Financial documents", "Identity/address proof"],
      opsRouting: "manual_ops_document_heavy",
      paymentModelHint: "Mid-to-high ticket guided filing",
      caseComplexity: "high",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official application center",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Caution flag: source is the official application center/operator rather than the embassy content itself.",
    },
  },
  {
    iso2: "TW", priorityRank: 17, launchBucket: "conditional_authorization",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "visa_required",
    policy: {
      productLabel: "Conditional Travel Authorization / visa route",
      officialSourceUrl: "https://www.roc-taiwan.org/in_en/cat/11.html",
      officialSourceSummary: "Taiwan's consular pages for India reference online Travel Authorization for eligible Indian nationals and separate visa application routes for other cases.",
      applyMode: "Conditional online authorization for eligible profiles; otherwise consular visa application.",
      stayValiditySummary: "Depends on whether traveller qualifies for the authorization path or needs a regular visa.",
      coreCustomerInputs: ["Passport biodata page", "Travel history or qualifying visa/residence details if applicable", "Travel dates", "Occupation details"],
      coreChecklist: ["Valid passport", "Photo", "Supporting eligibility documents", "Travel itinerary", "Application form"],
      opsRouting: "branching_logic_with_manual_review",
      paymentModelHint: "Mid-ticket guided screening plus filing",
      caseComplexity: "high",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official consular pages",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Do not oversimplify into a plain e-visa. Build a decision tree first.",
    },
  },
  {
    iso2: "HK", priorityRank: 18, launchBucket: "conditional_authorization",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "visa_free",
    policy: {
      productLabel: "14-day visa-free with mandatory Pre-arrival Registration",
      officialSourceUrl: "https://www.immd.gov.hk/eng/services/visas/pre-arrival_registration_for_indian_nationals.html",
      officialSourceSummary: "Hong Kong Immigration states that eligible Indian nationals visiting or transiting the HKSAR for up to 14 days must successfully complete Pre-arrival Registration (PAR).",
      applyMode: "Complete online PAR before travel; no visa needed for eligible short visits if PAR succeeds.",
      stayValiditySummary: "Up to 14 days per visit under the PAR route.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Personal details matching passport", "Transit or visit details"],
      coreChecklist: ["Valid passport with sufficient validity", "Successful PAR slip", "Return/onward travel", "Accommodation details if applicable"],
      opsRouting: "info_plus_light_digital_support",
      paymentModelHint: "Low-ticket assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official immigration department",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "PAR matching is exacting. Build a validation reminder around passport-field accuracy.",
    },
  },
  {
    iso2: "TR", priorityRank: 19, launchBucket: "digital_visa_growth",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "e-Visa or mission visa depending on eligibility",
      officialSourceUrl: "https://www.evisa.gov.tr/en/tour/",
      officialSourceSummary: "Türkiye's official e-Visa system says travellers can check online whether they are eligible for e-Visa; the MFA also says passport holders may obtain visas via evisa.gov.tr or Turkish missions.",
      applyMode: "Eligibility-screened e-Visa online, with mission/sticker route for cases that do not qualify.",
      stayValiditySummary: "Depends on the visa class and nationality-specific e-Visa eligibility result.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Supporting visas/residence permits if required by the e-Visa logic", "Contact details"],
      coreChecklist: ["Valid passport", "Eligibility proof where required", "Travel itinerary", "Payment method"],
      opsRouting: "branching_logic_with_manual_review",
      paymentModelHint: "Mid-ticket screening plus filing",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official e-visa portal + MFA guidance",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Do not promise e-Visa to every Indian applicant; flow should screen for eligibility first.",
    },
  },
  {
    iso2: "KE", priorityRank: 20, launchBucket: "digital_visa_growth",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "Electronic Travel Authorization (eTA)",
      officialSourceUrl: "https://etakenya.go.ke/",
      officialSourceSummary: "Kenya's official eTA portal says visitors should apply online for an Electronic Travel Authorization before travel.",
      applyMode: "Direct online eTA before travel.",
      stayValiditySummary: "Short-visit entry authorization route; exact stay depends on authorization and immigration grant.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Arrival details", "Accommodation details", "Photo if required by form"],
      coreChecklist: ["Valid passport", "Travel itinerary", "Accommodation", "Return/onward ticket", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket authorization assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official eTA portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Model as eTA, not legacy visa-on-arrival.",
    },
  },
  {
    iso2: "TZ", priorityRank: 21, launchBucket: "digital_visa_growth",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "eVisa",
      officialSourceUrl: "https://visa.immigration.go.tz/",
      officialSourceSummary: "Tanzania's electronic visa system allows travellers to complete the form, pay online, and submit their application electronically.",
      applyMode: "Online eVisa application through the immigration portal.",
      stayValiditySummary: "Tourism stay depends on the granted visa class and approval.",
      coreCustomerInputs: ["Passport biodata page", "Photo", "Travel dates", "Arrival point", "Accommodation details"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Accommodation", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official immigration portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Good candidate for a clean standardized eVisa flow.",
    },
  },
  {
    iso2: "QA", priorityRank: 22, launchBucket: "middle_east_conditional",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "visa_on_arrival",
    policy: {
      productLabel: "Visa on arrival / tourist visa depending on nationality rules",
      officialSourceUrl: "https://portal.moi.gov.qa/qatarvisas/",
      officialSourceSummary: "Qatar's official visa portal says citizens of more than 95 countries may enter on visa-on-arrival terms, while Visit Qatar notes tourist visas are available and some nationalities must pay a fee or apply prior to travel.",
      applyMode: "Check nationality-specific route first; may be free VOA, paid VOA, or tourist visa application depending on the current rules.",
      stayValiditySummary: "Route-specific; stay and fee depend on nationality and policy branch.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Hotel booking details", "Return ticket", "Existing residence/visa details if relevant"],
      coreChecklist: ["Valid passport", "Accommodation booking", "Return/onward travel", "Travel insurance if required", "Supporting funds"],
      opsRouting: "branching_logic_with_manual_review",
      paymentModelHint: "Mid-ticket screening and concierge support",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official visa portal + tourism portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "India-specific conditions can shift. Present a decision tree instead of a flat label.",
    },
  },
  {
    iso2: "OM", priorityRank: 23, launchBucket: "middle_east_digital",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "Tourist eVisa",
      officialSourceUrl: "https://evisa.rop.gov.om/",
      officialSourceSummary: "Oman's Royal Oman Police eVisa portal says visitors can apply for tourist visas online.",
      applyMode: "Online eVisa through the Royal Oman Police portal.",
      stayValiditySummary: "Depends on the visa type selected and approval granted.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Photo", "Accommodation details", "Travel itinerary"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Accommodation", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official evisa portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Oman is a clean eVisa case and should be easy to productize.",
    },
  },
  {
    iso2: "GE", priorityRank: 24, launchBucket: "conditional_authorization",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "e-Visa with conditional visa-free exceptions",
      officialSourceUrl: "https://www.evisa.gov.ge/",
      officialSourceSummary: "Georgia's official e-Visa portal says short-term visitors can apply online in three steps, while India-facing embassy pages also promote the e-Visa route.",
      applyMode: "Online e-Visa for eligible travellers; separate visa-free exceptions may apply for some Indians with qualifying visas or residence permits.",
      stayValiditySummary: "Depends on e-Visa approval and any alternative qualifying route.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Supporting visa/residence details if relevant", "Accommodation details"],
      coreChecklist: ["Valid passport", "Travel itinerary", "Accommodation", "Payment method", "Eligibility proof for any exception route"],
      opsRouting: "branching_logic_with_manual_review",
      paymentModelHint: "Mid-ticket guided screening plus filing",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official evisa portal + embassy page",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Build a branch for qualifying third-country visas/residence permits later.",
    },
  },
  {
    iso2: "KZ", priorityRank: 25, launchBucket: "easy_access_info",
    refreshPriority: "medium", refreshCadence: "monthly",
    visaCategory: "visa_free",
    policy: {
      productLabel: "14-day visa-free entry",
      officialSourceUrl: "https://www.gov.kz/memleket/entities/mfa/press/news/details/398648?lang=en",
      officialSourceSummary: "Kazakhstan says Indian citizens can enter visa-free for a continuous stay of up to 14 days, with a maximum of 42 days within every 180 days.",
      applyMode: "No prior visa needed for the visa-free short-stay route.",
      stayValiditySummary: "Up to 14 days per continuous stay, maximum 42 days in every 180 days.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Flight details", "Accommodation details"],
      coreChecklist: ["Valid passport", "Return/onward travel", "Accommodation", "Funds/supporting travel plan if requested"],
      opsRouting: "info_only_or_light_support",
      paymentModelHint: "Info-only or low-ticket travel support",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official government announcement",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Very good low-friction destination card for top-of-funnel traffic.",
    },
  },
  {
    iso2: "UZ", priorityRank: 26, launchBucket: "digital_visa_growth",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "e-Visa",
      officialSourceUrl: "https://e-visa.gov.uz/",
      officialSourceSummary: "Uzbekistan's official electronic visa portal is available for online visa applications; India-facing embassy guidance says electronic visas are available for Indian citizens.",
      applyMode: "Online e-Visa application before travel.",
      stayValiditySummary: "Depends on the granted e-Visa; India-facing guidance describes typical short tourist validity structures.",
      coreCustomerInputs: ["Passport biodata page", "Photo", "Travel dates", "Contact details"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official evisa portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Strong fit for a self-serve plus concierge flow.",
    },
  },
  {
    iso2: "PH", priorityRank: 27, launchBucket: "conditional_authorization",
    refreshPriority: "high", refreshCadence: "weekly",
    visaCategory: "visa_free",
    policy: {
      productLabel: "14-day visa-free; 30-day conditional visa-free with AJACSSUK visa/residence permit",
      officialSourceUrl: "https://evisa.gov.ph/page/policy",
      officialSourceSummary: "The Philippine DFA eVisa policy page says that from 08 June 2025 Indian nationals may enter visa-free for 14 days for tourism/business, and certain holders of valid AJACSSUK visas or residence permits may enter visa-free for 30 days for tourism.",
      applyMode: "Visa-free if conditions are met; otherwise apply for the appropriate Philippine visa.",
      stayValiditySummary: "14 days standard visa-free for eligible Indians; 30 days for qualifying AJACSSUK holders under the stated conditions.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Hotel booking", "Financial proof", "Qualifying AJACSSUK visa/residence permit details if applicable"],
      coreChecklist: ["Valid passport with required validity", "Confirmed hotel booking", "Proof of funds", "Return/onward ticket", "No derogatory immigration record"],
      opsRouting: "decision_tree_info_or_light_support",
      paymentModelHint: "Low-ticket screening or travel-readiness support",
      caseComplexity: "medium",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official DFA eVisa policy page",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "product_label must be separate from visa_category here.",
    },
  },
  {
    iso2: "KH", priorityRank: 28, launchBucket: "digital_visa_growth",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "e-Visa",
      officialSourceUrl: "https://www.evisa.gov.kh/",
      officialSourceSummary: "Cambodia's official eVisa site states the e-Visa fee, single-entry setup, three-month validity and one-month length of stay, with processing in three business days.",
      applyMode: "Online e-Visa before travel.",
      stayValiditySummary: "Single-entry e-Visa, validity 3 months, length of stay 1 month according to the official eVisa site.",
      coreCustomerInputs: ["Passport biodata page", "Photo", "Travel dates", "Entry point", "Accommodation details"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Accommodation", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official evisa portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Very automatable destination.",
    },
  },
  {
    iso2: "LA", priorityRank: 29, launchBucket: "digital_visa_growth",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "eVisa",
      officialSourceUrl: "https://laoevisa.gov.la/",
      officialSourceSummary: "Laos' official eVisa website presents a three-step online process: apply, pay, and download the eVisa approval from email.",
      applyMode: "Online eVisa before travel.",
      stayValiditySummary: "Depends on the approved eVisa class and Laos immigration conditions.",
      coreCustomerInputs: ["Passport biodata page", "Photo", "Travel dates", "Point of entry", "Accommodation details"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Accommodation", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official evisa portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Simple digital flow, good for automation.",
    },
  },
  {
    iso2: "MV", priorityRank: 30, launchBucket: "easy_access_info",
    refreshPriority: "medium", refreshCadence: "monthly",
    visaCategory: "visa_on_arrival",
    policy: {
      productLabel: "Tourist visa on arrival",
      officialSourceUrl: "https://immigration.gov.mv/visa/tourist-visa",
      officialSourceSummary: "Maldives Immigration states that tourist visa is granted on arrival and travellers do not require pre-approval, provided they satisfy the basic entry requirements.",
      applyMode: "No prior tourist visa approval needed; satisfy entry requirements and immigration clearance on arrival.",
      stayValiditySummary: "On-arrival tourist route; stay period depends on immigration grant and entry conditions.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Hotel booking", "Return ticket"],
      coreChecklist: ["Valid passport", "Accommodation confirmation", "Return/onward travel", "Sufficient funds or sponsorship evidence if required", "Traveller declaration"],
      opsRouting: "info_only_or_light_support",
      paymentModelHint: "Info-only or upsell travel support",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official immigration portal",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Good destination for lightweight assistance and cross-sells.",
    },
  },
  {
    iso2: "MU", priorityRank: 31, launchBucket: "easy_access_info",
    refreshPriority: "medium", refreshCadence: "monthly",
    visaCategory: "visa_free",
    policy: {
      productLabel: "Visa-free short visit",
      officialSourceUrl: "https://passport.govmu.org/passport/?page_id=605",
      officialSourceSummary: "Mauritius passport and immigration guidance says the tourist visa category allows a non-citizen to visit Mauritius for a short vacation stay; public guidance treats Indian ordinary passport holders as not requiring a prior visa for short visits.",
      applyMode: "No prior visa for ordinary short-visit tourism for Indian travellers; satisfy entry requirements on arrival.",
      stayValiditySummary: "Short-visit tourism route; practical stay grant depends on immigration conditions and return/onward arrangements.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Hotel booking", "Return ticket", "Financial proof"],
      coreChecklist: ["Valid passport", "Accommodation details", "Return/onward ticket", "Proof of funds", "Travel insurance if advised"],
      opsRouting: "info_only_or_light_support",
      paymentModelHint: "Info-only or low-ticket support",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official passport/immigration page + public references",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Keep confidence slightly lower because the cleanest India-specific rule is often surfaced via bilateral/travel advisories.",
    },
  },
  {
    iso2: "AZ", priorityRank: 32, launchBucket: "digital_visa_growth",
    refreshPriority: "medium", refreshCadence: "biweekly",
    visaCategory: "e_visa",
    policy: {
      productLabel: "eVisa",
      officialSourceUrl: "https://azerbaijan.vfsevisa.com/index.html",
      officialSourceSummary: "Azerbaijan's official eVisa site operated through the public VFS eVisa channel allows eligible travellers to apply online.",
      applyMode: "Online eVisa application before travel.",
      stayValiditySummary: "Depends on the eVisa product and the approved travel dates.",
      coreCustomerInputs: ["Passport biodata page", "Photo", "Travel dates", "Accommodation details", "Contact details"],
      coreChecklist: ["Valid passport", "Photo", "Travel itinerary", "Accommodation", "Payment method"],
      opsRouting: "mostly_digital_with_light_review",
      paymentModelHint: "Low-to-mid ticket eVisa assistance",
      caseComplexity: "low",
      humanReviewRequired: true,
      sourceConfidence: "medium",
      verifiedFrom: "official public evisa site",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "Treat as medium confidence until you independently verify the government/operator relationship more deeply.",
    },
  },
  {
    iso2: "RS", priorityRank: 33, launchBucket: "manual_consular",
    refreshPriority: "medium", refreshCadence: "monthly",
    visaCategory: "visa_required",
    policy: {
      productLabel: "Short-stay visa (C visa) / online consular route",
      officialSourceUrl: "https://www.mfa.gov.rs/en/citizens/travel-serbia/visa-requirements",
      officialSourceSummary: "Serbia's MFA says visa applications should be submitted personally to the Embassy or Consulate General abroad or online through the portal for foreign nationals.",
      applyMode: "Consular application, potentially with online initiation through the official foreigners portal.",
      stayValiditySummary: "Short-stay tourist/private-purpose visa route subject to consular decision.",
      coreCustomerInputs: ["Passport biodata page", "Travel dates", "Accommodation details", "Financial proof", "Travel insurance"],
      coreChecklist: ["Valid passport", "Application form", "Photo", "Accommodation proof", "Financial proof", "Travel medical insurance", "Return ticket"],
      opsRouting: "manual_ops_document_heavy",
      paymentModelHint: "Mid-ticket guided filing",
      caseComplexity: "high",
      humanReviewRequired: true,
      sourceConfidence: "high",
      verifiedFrom: "official MFA page",
      reviewStatus: "verified_seed",
      policyVersion: "2026-04-22-p2",
      internalOpsNotes: "India is NOT on a general visa-free tourist route here (correction from older internet lore).",
    },
  },
];

async function main() {
  console.log("🌍 Applying Phase 2 verified launch dataset (23 countries)...\n");

  for (const entry of PHASE2_DATA) {
    // Upsert country
    const country = await prisma.country.upsert({
      where: { code: entry.iso2 },
      create: {
        code: entry.iso2,
        name: entry.iso2, // placeholder — should already exist from seed-all-countries
        isActive: true,
        priorityRank: entry.priorityRank,
        launchBucket: entry.launchBucket,
        refreshPriority: entry.refreshPriority,
        refreshCadence: entry.refreshCadence,
        sortOrder: entry.priorityRank,
      },
      update: {
        priorityRank: entry.priorityRank,
        launchBucket: entry.launchBucket,
        refreshPriority: entry.refreshPriority,
        refreshCadence: entry.refreshCadence,
        sortOrder: entry.priorityRank,
      },
    });

    const verifiedAt = VERIFIED_AT;
    const nextDue = nextRefresh(entry.refreshCadence, verifiedAt);
    const freshness = computeFreshness(verifiedAt);
    const visaCategory = mapVisaCategory(entry.visaCategory) as any;

    // Find or create TOURIST policy
    const existing = await prisma.visaPolicy.findFirst({
      where: { countryId: country.id, visaType: "TOURIST", nationality: "IND" },
    });

    const policyData = {
      visaCategory,
      productLabel: entry.policy.productLabel,
      officialSourceUrl: entry.policy.officialSourceUrl,
      officialSourceSummary: entry.policy.officialSourceSummary,
      applyMode: entry.policy.applyMode,
      stayValiditySummary: entry.policy.stayValiditySummary,
      coreCustomerInputs: entry.policy.coreCustomerInputs,
      coreChecklist: entry.policy.coreChecklist,
      opsRouting: entry.policy.opsRouting,
      paymentModelHint: entry.policy.paymentModelHint,
      caseComplexity: entry.policy.caseComplexity,
      humanReviewRequired: entry.policy.humanReviewRequired,
      sourceConfidence: entry.policy.sourceConfidence,
      lastVerifiedAt: verifiedAt,
      nextRefreshDueAt: nextDue,
      freshnessStatus: freshness,
      verifiedFrom: entry.policy.verifiedFrom,
      reviewStatus: entry.policy.reviewStatus,
      policyVersion: entry.policy.policyVersion,
      phase: "phase_2",
      internalOpsNotes: entry.policy.internalOpsNotes,
    };

    if (existing) {
      await prisma.visaPolicy.update({ where: { id: existing.id }, data: policyData });
    } else {
      await prisma.visaPolicy.create({
        data: {
          countryId: country.id,
          visaType: "TOURIST",
          nationality: "IND",
          status: "ACTIVE",
          eligibilityRules: [],
          requiredDocuments: [],
          optionalDocuments: [],
          feeDetails: {},
          embassyLinks: [],
          ...policyData,
        },
      });
    }

    console.log(`  ✓ ${entry.iso2} — ${entry.policy.productLabel} [${entry.visaCategory}] freshness: ${freshness}`);
  }

  console.log("\n✅ Phase 2 dataset applied.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
